# Generated by Django 6.1 on 2026-09-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_employment_category_and_more'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('casual', 'Casual'), ('intern', 'Intern'), ('nysc', 'NYSC'), ('expatriate', 'Expatriate')], max_length=20, null=True)),
                ('employment_category', models.CharField(blank=True, choices=[('staff', 'Staff'), ('management', 'Management'), ('executive', 'Executive')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('minimum_years_of_service', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_years_of_service', models.PositiveIntegerField(blank=True, null=True)),
                ('allocated_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_policies', to='employees.department')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='leave.leavetype')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_policies', to='employees.position')),
            ],
            options={
                'ordering': ['leave_type__name', 'department__name', 'position__name'],
            },
        ),
    ]
