# Generated by Django 6.1 on 2026-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest_request_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'permissions': [('approve_leave', 'Can approve leave requests')]},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
