# Generated by Django 6.1 on 2026-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hostel_room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
