# Generated by Django 6.1 on 2026-08-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_hostel_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('yunatt', 'Yunatt / TIMY'), ('device', 'Direct Device'), ('other', 'Other')], default='yunatt', max_length=30)),
                ('source_identifier', models.CharField(default='cloud', help_text="Use 'cloud' for Yunatt cloud IDs, or a device serial number for device-specific IDs.", max_length=120)),
                ('external_user_id', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_identities', to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('system', 'source_identifier', 'external_user_id'), name='unique_biometric_identity')],
            },
        ),
    ]
