# Generated by Django 6.1 on 2026-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_biometricidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='required_staff',
            field=models.PositiveIntegerField(default=0, help_text='Normal number of employees required for daily operations.'),
        ),
    ]
