# Generated by Django 6.1 on 2026-09-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_department_required_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_category',
            field=models.CharField(choices=[('staff', 'Staff'), ('management', 'Management'), ('executive', 'Executive')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('casual', 'Casual'), ('intern', 'Intern'), ('nysc', 'NYSC'), ('expatriate', 'Expatriate')], default='permanent', max_length=20),
        ),
    ]
