# Generated by Django 6.1 on 2026-08-31 19:04

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_biometricidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('appointment', 'Appointment Letter'), ('contract', 'Employment Contract'), ('national_id', 'National ID'), ('passport', 'International Passport'), ('drivers_license', "Driver's Licence"), ('passport_photo', 'Passport Photograph'), ('medical', 'Medical Certificate'), ('guarantor', 'Guarantor Form'), ('certificate', 'Certificate'), ('promotion', 'Promotion Letter'), ('warning', 'Warning Letter'), ('termination', 'Termination Letter'), ('other', 'Other')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=documents.models.employee_document_path)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
