# Generated by Django 6.1 on 2026-08-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('factory', 'Factory'), ('hostel', 'Hostel'), ('office', 'Office')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_overnight', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_clock_in', models.DateTimeField(blank=True, null=True)),
                ('actual_clock_out', models.DateTimeField(blank=True, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_departure_minutes', models.PositiveIntegerField(default=0)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'Leave'), ('incomplete', 'Incomplete')], default='present', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='employees.employee')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('late', 'Late Arrival'), ('early_departure', 'Early Departure'), ('absence', 'Absence'), ('missing_clock_in', 'Missing Clock In'), ('missing_clock_out', 'Missing Clock Out'), ('hostel_violation', 'Hostel During Shift')], max_length=30)),
                ('minutes_affected', models.PositiveIntegerField(default=0)),
                ('proposed_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('waived', 'Waived'), ('held', 'Held')], default='pending', max_length=20)),
                ('employee_reason', models.TextField(blank=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='attendance.dailyattendance')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.shift')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('verification_type', models.CharField(choices=[('face', 'Face'), ('fingerprint', 'Fingerprint'), ('card', 'Card'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('external_event_id', models.CharField(blank=True, max_length=150, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='employees.employee')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='attendance.biometricdevice')),
            ],
            options={
                'ordering': ['timestamp'],
                'constraints': [models.UniqueConstraint(fields=('device', 'external_event_id'), name='unique_device_external_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_daily_employee_attendance'),
        ),
    ]
